services:
  redis:
    image: redis:6.0-alpine 
    container_name: redis
    ports:
      - "6380:6379"
  db:
    image: postgres:14
    container_name: postgres_db
    hostname: postgres_db
    env_file:
      - ./.environment/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangoApi
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - ./.environment/.django
volumes:
  postgres_data: